### ISSUE TITLE
REQ

### ISSUE THREAD

**Issue by asagishi** [yasawibu/linksbypasser#21]
Plantaheim.web.id = http://plantaheim.web.id/herbs/centella-asiatica-useful-plant-for-mind-workers/?d=aHR0cHM6Ly93d3cxMDYuemlwcHlzaGFyZS5jb20vdi9yY2I1TlZ0dy9maWxlLmh0bWw=#landing
sama hexafile.net dong = https://hexafile.net/4F9xq

**Comment by asagishi** [comment]
plantaheim udh ada tpi gk work ..

**Comment by yasawibu** [comment]
@asagishi 
Untuk plantaheim saya coba link di atas ke bypass kok.
Mohon dicoba sekali lagi, kalau tetap tidak bisa, silakan di-screenshot.

Sedangkan untuk hexafile, nanti saya tambahkan.
Terima kasih.
