### ISSUE TITLE
[Request] autech.xyz

### ISSUE THREAD

**Issue by rigaz29** [yasawibu/linksbypasser#26]
https://autech.xyz/lenovo-a7010/?url=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2ZpbGUvZC8wQjhnZmZ2VWE2RWdoWTBSRVRsOWlZbXRIVmxrL3ZpZXc/dXNwPXNoYXJpbmc=

**Comment by yasawibu** [comment]
@rigaz29 
Added to v0.4.4
Please update your linksbypasser.

Thanks for the info~
