### ISSUE TITLE
[Req] www.urlku.gq

### ISSUE THREAD

**Issue by rigaz29** [yasawibu/linksbypasser#27]
https://www.urlku.gq/p/life-with-woody-10-inspirational-quotes.html?url=IyNPRkFaSSU0MCU1QiUxNVglNUIlNUQlMTdfTUElNUUlMDdDRH4lNjAlNUNFcUElMTFEJTdDbXolMThxJTQwT20lMUVJJTdEJTVFTk5PJTEwaiUxOCUwN0wlMDdNREFOJTA3RUdLJTA2TURPR0dPJTA2TSU1RUFaTCUwNyUwNyUxMiU1QlglNUMlNUMlNDAjIw%3D%3D

**Comment by yasawibu** [comment]
I can't bypass this type of link yet.
It need more time to understand the code, but right now i'm too busy and don't have much time for that.

So, for now, I've label it as help wanted and low priority.
Thanks~

**Comment by yasawibu** [comment]
Link sudah di-support pada linksbypasser v0.4.5.
Silakan update linksbypasser ke versi terbaru.

Terima kasih~
