### ISSUE TITLE
Buatin yg kyk gini dong bos

### ISSUE THREAD

**Issue by falfan2018** [yasawibu/linksbypasser#29]
di firefox klo bisa
ampuh bgt nih bypassnya
https://chrome.google.com/webstore/detail/adfly-killer/jipinfggejlkpkomnccoocbdndjalicp?hl=en

**Comment by yasawibu** [comment]
@falfan2018 
Ini maksudnya bagaimana, ya?
Jadiin linkbypasser ini ke ekstensi chrome dan add ons firefox? Atau gimana?

**Comment by alvahn** [comment]
bypass hmpir smua link shortener tnpa masuk ke web shortener nya

**Comment by yasawibu** [comment]
@alvahn
Setelah baca-baca deskripsinya, "sepertinya" cara kerjanya seperti ini: 
pc client -> akses link -> ekstensi chrome baca linknya terus dioper ke pc server
pc server -> akses link yang dioper -> bypass link -> link asli
pc server nyalin link aslinya terus dioper ke pc client untuk diakses

Nah, berhubung saya belum belajar kirim data ke server dan tidak punya server, jadi untuk saat ini saya tidak bisa membuat yang seperti itu.

Dan untuk link shortener lain yang belum linksbypasser support, silakan gabungkan pemakaian linksbypasser dengan bypasser-bypasser lainnya.

Terima kasih.
