### ISSUE TITLE
Request 

### ISSUE THREAD

**Issue by falfan2018** [yasawibu/linksbypasser#30]
bos buatin yg kyk gini donk auto download helper dibnyak filehosting klo bypass timer & shortener uda bnyak bgt yg buat
contoh nya yg kyk gini 
https://openuserjs.org/scripts/vachzar/Various_Filehosting_Download_Helper
https://github.com/idoenk/maknyos-autoin
2 project diatas ama developernya g dimaintenance lg jd bnyak yg error n g work

**Comment by yasawibu** [comment]
@falfan2018 
Saya coba yang maknyos di 4shared sama zippy, gak bisa.
Terus nyoba yang download helper, tampilan zippy jadi berubah dan otomatis ke-download.

Jadi intinya, script itu fungsinya untuk otomatis klik download?
Kalau iya, mungkin saya bisa buat kalau masih sesederhana kayak zippy.

Maka dari itu, saya ingin tahu dulu, file hosting apa saja yang anda inginkan untuk di-support.
Bisa kasih saya contoh 3 file hosting?

**Comment by alvahn** [comment]
@yasawibu btw kpn om dibuatin scriptnya

**Comment by yasawibu** [comment]
@alvahn Sebenarnya scriptnya sudah lama jadi (karena fiturnya mirip linksbypasser), tapi baru support zippyshare saja. Karena itu belum saya publikasikan.

FYI, sebenarnya saya sedang sibuk ngurus berkas pascasidang skripsi.
Jadi, untuk proyek tersebut masih saya pending.
Nanti kalau sudah beres semua, baru akan saya kerjakan lagi.

**Comment by yasawibu** [comment]
@falfan2018 @alvahn 
Saya sudah buatkan projectnya, namun baru support 2 file hosting saja.
https://github.com/yasawibu/yasa-download-helper

Silakan buka issue di sana saja, supaya issue di sini bisa saya close.
Terima kasih.
