### ISSUE TITLE
Request bypass 

### ISSUE THREAD

**Issue by falfan2018** [yasawibu/linksbypasser#32]
http://lanjutinaja.net/5-bahaya-begadang-bagi-kesehatan-tubuh/?wp_safelink_data=NzBlZmRmMmVjOWIwODYwNzk3OTVjNDQyNjM2YjU1ZmIqWXlvcVpUaWxIV3QxZkt2TVhEaDVmNVVXaXNXTU1uQkhUWE9KdWY1b3ZMaExoK0wyN2hLenNlbithUHY5aDBxdEkzYUVmbWdhdjlQL2ZidkRYM0lMdnc9PQ==#landing

http://www.animanganews.com/p/5-things-to-look-for-before-starting.html?url=IyNrRiU1QyU1QyUxQiUwN0UlMDdFR0slMDZNS0laR1paQUUlMDclMDclMTIlNUJYJTVDJTVDJTQwIyM%3D

**Comment by yasawibu** [comment]
@falfan2018 
Link akan saya proses.

Lain kali, dimohon untuk membuka issue yang terpisah untuk dua/lebih link yang berbeda.
Terima kasih~

**Comment by yasawibu** [comment]
Link sudah di-support pada linksbypasser v0.4.5.
Silakan update linksbypasser ke versi terbaru.

Terima kasih~

**Comment by alvahn** [comment]
@yasawibu yg safelink template kok g auto klik button bos klo kyk gtu scriptnya sma universal bypass

**Comment by yasawibu** [comment]
@alvahn 
Safelink template? Yang mana?
Bisa lebih detail lagi? Link yang dimaksud yang mana?
Kalau 2 link di atas, di tempat saya bisa ke-bypass semua kok.

Btw, karena saya tidak tahu nama template-template yang dipakai, jadi langsung sertain linknya saja.
Tambah screenshot lebih bagus lagi.

Mengingat waktu respon saya yang tidak begitu cepat, saya harap bisa kasih info yang detail biar bisa cepat saya proses.

Terima kasih~

**Comment by alvahn** [comment]
@yasawibu oh sorry bos ternyata gara" extension bypass  lain mknya g langsung auto klik button

**Comment by yasawibu** [comment]
@alvahn 
Sip.
Kalau begitu, issue ini saya tutup lagi.

Terima kasih~
