### ISSUE TITLE
Bug link not found 

### ISSUE THREAD

**Issue by alvahn** [yasawibu/linksbypasser#35]
http://landscapenature.pw/?id=NW84MTVlZnplRGNVeGY0WXNybExFNEVPcW1yM2RVTTVhMTh6ZHNFUzUzMUpPK2FmeTUvTDRpRnpVY0lKbnp4emtrSk4xZU9tOWk2MFJPbjgrSGo1S0E9PQ==

https://bagilagi.com/cara-mengobati-tekan-darah-tinggi-secara-alami/

dll soralink plugin template pokoknya
linkbypasser v 0.5.0

**Comment by yasawibu** [comment]
@alvahn 
Makasih buat link landscapenature.pw-nya.
Saya gak punya linknya, jadi gak bisa ngetes.
Fix di v0.5.1 nanti.

Untuk yang bagilagi.com, itu memang linknya yang kurang.
Coba matiin linksbypassernya, terus buka link itu, pasti gak ada link tujuannya.
Saya coba link yang di TESTED-LINKS, kebypass kok.
https://bagilagi.com/?id=U3ZCaGl2d0lOTmNvbkNGczdtUmMyWkhod0NxWDQ3K3R1VTdPZmhmcUtoSGcxMy9tYjBkMDFvRmUrdC8wdWNVK1JtQWNrdUI3WnRPNys3NHMrcWJBelRlL0xSZmplRnVFZ1BYMDBvTVNxWFU9

Kalau ada link bagilagi yang gak ke bypass, coba share linknya.

"dll soralink plugin template pokoknya", saya tidak punya linknya, jadi saya tidak bisa bantu apa-apa soal link "dll" tersebut.

Terima kasih~

**Comment by alvahn** [comment]
@yasawibu ane kmaren uda nemu 4x link kyk gtu klo dinonaktifin work tp lupa ntr klo ketemu ane report lg

**Comment by yasawibu** [comment]
@alvahn 
Sip.
Kalau bisa, sekalian share web tempat dapet linknya, supaya bisa saya cek variasinya.
Misal:
Waktu buka contohwebsite.com -> di sana ada link umpetin.com yang mau dibypass.
Nah, share link contohwebsite.com dan umpentin.com-nya.

**Comment by alvahn** [comment]
@yasawibu http://getinfos.net/?id=SVl3ZG53RzhmRHVlWjAwYyswdk5QQ0JGOFpOQnJpNVhFcDNJTTA1UVk2RTk2YjJObHlqRGo1REh2eFJkOG5wbFhMSldQcm5BR2FocHNhT0VDTCtoTWd5WlIxNWFTbE5nYzQvQ1BrNk93WG89

ada lg

**Comment by yasawibu** [comment]
@alvahn 
Lain kali, bikin issue baru lagi aja.
Jangan comment di issue yang udah di close, apalagi beda link.
Mending bikin "[Bug] getinfos.net", biar lebih rapi.

Btw, makasih atas infonya ^^
