### ISSUE TITLE
[Request] www.mirrored.to

### ISSUE THREAD

**Issue by alvahn** [yasawibu/linksbypasser#41]
https://www.mirrored.to/files/1PBKKFYA/

click to view the file links dan yg pda saat pilih filehosting

**Comment by yasawibu** [comment]
@alvahn 
www.mirrored.to memang belum di-support, jadi masuknya ke [request], ya.
Untuk situs tersebut akan di-support di versi 0.6.0.
Mohon untuk bersabar m(_ _)m

**Comment by yasawibu** [comment]
Sudah ditambahkan pada v0.6.0.
Terima kasih.
