### ISSUE TITLE
[Request] bolaoke.club

### ISSUE THREAD

**Issue by alvahn** [yasawibu/linksbypasser#42]
http://www.bolaoke.club/prediksi-barcelona-vs-real-madrid-laga-adu-gengsi/?get=MSt5ekN5eVFoUXlYaEwvRXppNEd2REVMdVU3aEJqWmJld2lsbXVOMXRhdz0=#landing

**Comment by yasawibu** [comment]
Sudah di-support di v0.5.4.
Silakan update LinksBypasser-nya.

Thanks for the info~ ^^
