### ISSUE TITLE
[Request] insurance-waifu.cf

### ISSUE THREAD

**Issue by alvahn** [yasawibu/linksbypasser#45]
http://insurance-waifu.cf/?u=nplfXAxsInaHR0cDovL3d3dzcwLnppcHB5c2hhcmUuY29tL3YvT2tHdVdpZjQvZmlsZS5odG1s

http://insurance-waifu.cf/post/6%20Asuransi%20Terb-5608

**Comment by yasawibu** [comment]
Telah ditambahkan pada v0.5.5.
Thanks for the info~ ^^
