### ISSUE TITLE
[Request] https://mirrorace.com

### ISSUE THREAD

**Issue by alvahn** [yasawibu/linksbypasser#46]
https://mirrorace.com/m/1s9b5

**Comment by yasawibu** [comment]
@alvahn 
Mirrorace sudah di-support kok.
Saya sudah coba linknya, ke-bypass kok.
Itu kan harus milih hostnya dulu, baru ke-bypass.

**Comment by alvahn** [comment]
@yasawibu oh iya gan kmaren pas nyoba ane matiin scriptnya sorry

**Comment by Anjaymantap** [comment]
kalau ada captchanya ngga bisa yah ?
