### ISSUE TITLE
[Bug] http://apasih.pw

### ISSUE THREAD

**Issue by alvahn** [yasawibu/linksbypasser#47]
http://apasih.pw/?id=N212MG1obUJ1eDlha3JLN3dnWUFweE54QVFTWXNPcWZCaHNxZjFrcTRMSitLdWl4eWZITlJFNEh3N1kwNWZnMQ==

**Comment by yasawibu** [comment]
Telah diperbaiki pada v0.5.5.
Thanks for the info~ ^^
