### ISSUE TITLE
[bug] http://bagilagi.com & http://davinsurance.com

### ISSUE THREAD

**Issue by alvahn** [yasawibu/linksbypasser#49]
http://bagilagi.com/?id=U3ZCaGl2d0lOTmNvbkNGczdtUmMyWkhod0NxWDQ3K3R1VTdPZmhmcUtoRURGT1E3M0Y5aVk3eVdKZHZSY3ZpdHFMMHk1ekVUbEYzRUVHT3pLZWNSWVNMTGVIMklJY2E1OG92Y3BsL3ExVUk9

http://davinsurance.com/XRox5JlVTBJHqvUeyO6Tl3ERAYZcjwXqGeZCXRnEt5yjThr+4o9rRJC9Ax/Vc3tD4UWoQkiw00/nOfgRw9T4xrtLEM45WS6T7ppyFCpVfWlvmdlrT1Tkt7cEQFsEZ0E0+QeqJgRkCGAH0rgcHD8RD9g5aLNYQEr2FdUWO1Jjx7nqExtMZ837xtiCmrZckNTR39GKJ1qTNM6qbBHW330Y+g==

**Comment by yasawibu** [comment]
@alvahn 
Yang bagilagi, di saya bisa kok.
Coba dibuka lagi. Kalau tetap tidak bisa, coba jelaskan ciri-cirinya seperti apa.

Untuk yang davinsurance, memang linknya yang bermasalah.
Saya coba matikan linksbypassernya, artikelnya not found.
Coba cari link davinsurance lain untuk dijadikan pembanding.

Btw, internetnya pakai telkomsel, bukan?

**Comment by alvahn** [comment]
@yasawibu iya pke telkomsel itu link baru

**Comment by alvahn** [comment]
@yasawibu

**Comment by alvahn** [comment]
@yasawibu  nih link baru smua 
http://davinsurance.com/Ua66Ed/JH/W3IS3ZDrVZtvuzrR30V7VswdbnuqHaD3CLuOMMspxbt9+F7qtQRglUbqoCS/QAF3sBL7Fg24wFNw==
http://davinsurance.com/eUKjfGB5vctrWvOsVByCj+Ep34MOqnzTZgl4AMP6vc7FQN3LIKCvnU7sjaK8vj1TRklOlkERwbk0p1T8pcZfpU+xDt2IDnjKTcpKccg1qv7J58JEl52ypvKKYvxtc4uEB8EnyVy6iYkgF5nMaq4skQkgdUaEh3ueiPEz+fjdrfgfSgdON1kSHDiv0umCFdaEYxsVdMhGc0dL5WgGNnG9Kg==
http://davinsurance.com/XRox5JlVTBJHqvUeyO6Tl5assW3vUgihK7CAc4WTNnt5lXqeLMtqpjir2au2l+c3M9hx+SMV7Flz57KN1r0JV8X2/7WYFOyiQ/ZPqBToyE4Rjhl19Eqp2/Gb+i8IOQ7giZjrWxQQpydaOzQhZQaATT3aP8NcOL9spd1C8+Wx63MOhn8itljGXrzSvKm7ZLCPHCbw+O6TJN/+7tsXkxz+TA==

**Comment by yasawibu** [comment]
@alvahn 
Kalau pake telkomsel, kadang suka gagal karena bentrok sama iklan inject-an telkomsel (bisa cek intrusive ads telkomsel di google).
Solusinya, refresh situsnya sekali lagi untuk mastiin apakah linksbypassernya yg ngebug atau gara-gara telkomsel ads.

Untuk yang davinsurance, saya sudah coba semua link di atas hasilnya not found terus.
![screenshot from 2018-08-23 21-07-22](https://user-images.githubusercontent.com/36402967/44530499-b7d45600-a718-11e8-8d2a-b2b0d4bf6234.png)
Coba kasih saya situs dapetin link davinsurance supaya bisa saya proses.

**Comment by alvahn** [comment]
@yasawibu http://meownime.com

**Comment by yasawibu** [comment]
@alvahn 
Sudah diperbaiki pada v0.6.0.
Thanks for the info~ ^^
