### ISSUE TITLE
[Request] drivefiles.bid & drive.jepitkertas.com

### ISSUE THREAD

**Issue by alvahn** [yasawibu/linksbypasser#59]
https://drivefiles.bid/link-1/?site=aHR0cDovL2JpdC5seS8yemwxSnFi#LinkDL

https://drive.jepitkertas.com/download/?site=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL3VjP2V4cG9ydD1kb3dubG9hZCZpZD0wQjhWRjJjSDV0ekZWTVZWRmRUSnNaa3RMZVZF

**Comment by yasawibu** [comment]
Done, yah.
Thanks atas infonya ^^
