### ISSUE TITLE
Request https://kurosafety.menantisenja.com

### ISSUE THREAD

**Issue by alvahn** [yasawibu/linksbypasser#61]
https://kurosafety.menantisenja.com/?site=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL29wZW4/aWQ9MThsQ09WUC1heWpQaXA1T0RUVlVoSTR4eHRDUUlzdkxM

https://pafpaf.info/?site=aHR0cHM6Ly93d3czOS56aXBweXNoYXJlLmNvbS92L08yUlR5ZmpDL2ZpbGUuaHRtbA==

**Comment by yasawibu** [comment]
@alvahn 
Sudah saya tambahkan pada v0.6.8.
Terima kasih atas informasinya ^^
