### ISSUE TITLE
[request] http://irisvera.com

### ISSUE THREAD

**Issue by oranglewat** [yasawibu/linksbypasser#63]

**Comment by oranglewat** [comment]
tolong ditambahkan ya gan ini url lengkap nya
http://irisvera.com/?r=aHR0cHM6Ly93d3c0My56aXBweXNoYXJlLmNvbS92L2tiQU9oZDVZL2ZpbGUuaHRtbA==
thanks

**Comment by yasawibu** [comment]
@oranglewat 
Oke, besok akan saya update.
Makasih atas informasinya ^^

**Comment by yasawibu** [comment]
@oranglewat 
Sudah saya tambahkan.
Silakan update ke versi terbaru.
Terima kasih atas kontribusinya ^^

**Comment by oranglewat** [comment]
makasih gan sudah saya coba bisa. mantap jiwa
