### ISSUE TITLE
[Request] http://lonelymoon.net/

### ISSUE THREAD

**Issue by horrebb** [yasawibu/linksbypasser#66]
http://lonelymoon.net/?id=NGVQNW9PQ29iOEdCanhYdWFyMTZDVVdiT0FOT3lSRitFUm5VNFdyUG45Yz0=

**Comment by yasawibu** [comment]
@horrebb 
That link now supported on v0.7.0.
Please update your linksbypasser.

Thanks for your contribution ^^
