### ISSUE TITLE
[Request] suarankri.me

### ISSUE THREAD

**Issue by nggomaen** [yasawibu/linksbypasser#78]
suarankri.me tolong ditambakhan gan
suarankri.me ini termasuk SafelinkU gan, tapi udah sy coba masukin ke case safelinku gak work, mungkin karena tampilannya pagenya udah beda. tapi kalau url suarankri.me nya sy ubah manual di address bar jadi idsly.bid dia bisa ke-bypass ikut rule safelinku
Contoh link:
http://suarankri.me/nZaN1a

**Comment by yasawibu** [comment]
Done yah.
Thanks infonya ^_^
