### ISSUE TITLE
linkk.bid

### ISSUE THREAD

**Issue by asagishi** [yasawibu/linksbypasser#9]
tambahin linkk.bid gan

**Comment by yasawibu** [comment]
linkk.bid sudah support sejak v0.3.0.
Link yang diuji: http://linkk.bid/zyCJp7

Coba dicek versi linksbypassernya udah terbaru atau belum.
Kalau memang tetap tidak bisa di-bypass, coba sertakan linknya di sini untuk dijadikan sampel.

Terima kasih.

**Comment by asagishi** [comment]
oh iya bisa di bypass .. kemarin kenapa yak kok gk bisa .. hehe .. sry sry
